# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  network:

services:

  # Set up our actual network
  orderer.biswas.com:
    extends:
      file:   base.yaml
      service: orderer
    networks:
      - network

  peer0.grower.biswas.com:
    extends:
      file:  grower.yaml
      service: peer0
    networks:
      - network
  peer1.grower.biswas.com:
    extends:
      file:  grower.yaml
      service: peer1
    networks:
      - network
      
  peer0.producer.biswas.com:
    extends:
      file:  producer.yaml
      service: peer0
    networks:
      - network
  peer1.producer.biswas.com:
    extends:
      file:  producer.yaml
      service: peer1
    networks:
      - network

  # Add an extra container for interacting with it
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      # the following 3 env vars determine the peer used when running
      # e.g. `peer channel create` from inside the container
      - CORE_PEER_ADDRESS=peer0.grower.biswas.com:7051
      - CORE_PEER_LOCALMSPID=GrowerMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/artifacts/certs/peerOrganizations/grower.biswas.com/users/Admin@grower.biswas.com/msp
    working_dir: /opt/gopath
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts:/opt/gopath/artifacts/
        # - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        # - ./scripts:/opt/gopath/scripts/
    depends_on:
      - orderer.biswas.com
      - peer0.grower.biswas.com
      - peer1.grower.biswas.com
      - peer0.producer.biswas.com
      - peer1.producer.biswas.com
    networks:
      - network
